//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHT.CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSubModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemSubModule()
        {
            this.SystemRoleAuthorities = new HashSet<SystemRoleAuthority>();
        }
    
        public int Id { get; set; }
        public string SubName { get; set; }
        public Nullable<int> TopId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemRoleAuthority> SystemRoleAuthorities { get; set; }
        public virtual SystemTopModule SystemTopModule { get; set; }
    }
}
