//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHT.CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Customer
    {
        public int Id { get; set; }
        public Nullable<int> CId { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<int> MId { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
        public string CusCode { get; set; }
        public string CusName { get; set; }
        public Nullable<int> SaleId { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string BussinessType { get; set; }
        public string Scale { get; set; }
        public string CusType { get; set; }
        public string PhoneNum { get; set; }
        public string HomePage { get; set; }
        public string Address { get; set; }
        public Nullable<byte> IsPublisCus { get; set; }
    }
}
