//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHT.CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Visit
    {
        public int Id { get; set; }
        public Nullable<int> CId { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<int> MId { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
        public Nullable<int> CusId { get; set; }
        public Nullable<int> ConId { get; set; }
        public string VTitle { get; set; }
        public string VContent { get; set; }
        public string VType { get; set; }
        public Nullable<System.DateTime> VPlanDate { get; set; }
        public Nullable<System.DateTime> VCompleteDate { get; set; }
        public Nullable<System.DateTime> VSuperiorDate { get; set; }
        public string VSuperiorSuggestion { get; set; }
        public Nullable<int> VSuperiorId { get; set; }
        public Nullable<bool> VStatus { get; set; }
    }
}
