//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHT.CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLogin
    {
        public int Id { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<int> IsLock { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
    }
}
